db.taxonomymodel.insertOne({ "code": "Lomon. Henkelio", "desc": "Письмо Генкелю И.-Ф вторая половина декабря 1739", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Formeyo", "desc": "Письмо Формею И.-Г.-С 12 февраля 1754", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Zanotto", "desc": "Письмо Цанотти Ф.-М 9 мая 1764", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Eulero (1)", "desc": "Письмо Эйлеру Л 16 февраля 1748", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Eulero (2)", "desc": "Письмо Эйлеру Л 5 июля 1748", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Eulero (3)", "desc": "Письмо Эйлеру Л 27 мая 1749", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Eulero (4)", "desc": "Письмо Эйлеру Л 12 февраля 1754", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Eulero (5)", "desc": "Письмо Эйлеру Л 28 ноября 1754", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Or. de gener. metall.", "desc": "Слово о рождении металлов от трясения земли", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. De motu aeris", "desc": "De motu aeris in fodinis observato. Auct. M. Lomonosow", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Medit. brev. de evapor. mercur.", "desc": "Meditatio brevis de evaporatione mercurii die 7 maji 1761", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Comm. de instr. caust. catoptr.-dioptr.", "desc": "Commentatio de instrumento caustico catoptrico-dioptrico", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. De motu aeris [breve]", "desc": "De motu aeris in fodinis observato. [Краткое содержание]", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. De partic. phys. insensib. corp. natur. constit.", "desc": "De particulis physicis insensibilibus corpora naturalia constituentibus", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. De tinct. metall.", "desc": "De tincturis metallorum. Auctore Michaele Lomonosow", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Diss. de act. menstr. chymic. in gen. [breve]", "desc": "Dissertatio de actione menstruorum chymicorum in genere. Auct. M. Lomonosow [Краткое содержание]", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Diss. phys. de corp. mixt. differ.", "desc": "Dissertatio physica de corporum mixtorum differentia", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Elem. chim. math.", "desc": "Elementa chimiae mathematicae", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Spec. phys. de transmut. corp. solid.", "desc": "Specimen physicum de transmutatione corporis solidi in fluidum a motu fluidi praeexistentis dependente", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. [276 not. de phys. et philos. corpusc.]", "desc": "[276 заметок по физике и корпускулярной философии; темы будущих работ]", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. [44 not. de cohaes. corp.]", "desc": "[44 заметки о сцеплении корпускул]", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. [de partic. insensib. corp. deque caus. qualit. partic. in gen.]", "desc": "[Tentamen theoriae de particulis insensibilibus corporum deque causis qualitatum particularium in genere]", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. [not. de gravit. corp.]", "desc": "[Заметки о тяжести тел]", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Anemometrum", "desc": "Anemometrum summam celiritatem cujusvis venti et simul variationes directionum illius indicans. Auctore Michaele Lomonosow", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Consilium de constr. barometr. univers.", "desc": "Consilium de construendo barometro universali proponitur clarissimis academicis auctore Michaele Lomonosow", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });

db.taxonomymodel.insertOne({ "code": "Lomon. Diss. de gen. et nat. nitri", "desc": "Dissertatio de generatione et natura nitri", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Medit. de cal. et frig. caus.", "desc": "Meditationes de caloris et frigoris causa auctore Michaele Lomonosow", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Medit. de cal. et frig. caus. [breve]", "desc": "Meditationes de caloris et frigoris causa auctore Michaele Lomonosow [Краткое содержание]", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Prodr. ad ver. chym. phys.", "desc": "Prodromus ad veram chymiam physicam", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Suppl. ad diss. de vi aer. elast. [breve]", "desc": "Supplementum ad diss. de vi aeris elastica [Краткое содержание]", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Suppl. ad medit. de vi aer. elast.", "desc": "Supplementum ad meditationes de vi aeris elastica", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Tent. theor. de vi aer. elast.", "desc": "Tentamen theoriae de vi aeris elastica", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Tent. theor. de vi aer. elast. [breve]", "desc": "Tentamen theoriae de vi aeris elastica [breve]", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Tent. chym. phys. p. I", "desc": "Tentaminis chymiae physicae pars prima", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. De grav. corp. et motu primit.", "desc": "[О тяжести тел и об извечности первичного движения]", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. [Quat.cas.]", "desc": "[План опытов с универсальным барометром]", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. [Ad Chym. Phys.]", "desc": "[Планы и материалы к курсу физической химии]", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. [Ad diss. de nitr.]", "desc": "[Расчет к диссертации о рождении и природе селитры]", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Contra caud. vapor. comet.", "desc": "Contra caudam vaporosam cometarum", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. De rat. quant. mat. et pond.", "desc": "De ratione quantitatis materiae et ponderis", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Diss. de liq. et solid.", "desc": "Dissertatio de liquido et solido", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Medit. brev. de evapor. mercur.", "desc": "Meditatio brevis de evaporatione mercurii die 7 maji 1761", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Medit. de solid. et fluid.", "desc": "Meditationes de solido et fluido", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Nova method. observ. refract. radiorum", "desc": "Nova methodus observandi refractiones radiorum in omni genere pellucidorum corporum", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Orat. de Met. Electr.", "desc": "Oratio de meteoris vi electrica ortis", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Orat. de Met. Electr. Expl.", "desc": "Orationis de meteoris electrics explanationes", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Programma", "desc": "Programma", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Theor. electric. meth. mathem. concinn.", "desc": "Theoria electricitatis methodo mathematica concinnata (1756)", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. [127 not. ad theor. luc. et electric.]", "desc": "[127 заметок к теории света и электричества]", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });

db.taxonomymodel.insertOne({ "code": "Lomon. [Ad praem. 1753]", "desc": "[Задача на премию Петербургской Академии Наук на 1753 г.]", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. [Ad praem. 1760]", "desc": "[Задачи на премию Петербургской Академии Наук на 1760 г.]", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. [Not. ad Physic. syst. et Microlog.]", "desc": "[Заметки к «Системе всей физики» и «Микрологии»]", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. [De congelat. mercur.]", "desc": "[Записка об опытах по замораживанию ртути]", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. [Respons. ad dub. et confirm. theor. de caud. comet.]", "desc": "[Материалы обсуждения «Слова о явлениях воздушных, от электрической силы происходящих»]", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. [De nat. luc.]", "desc": "[О природе света]", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. [De electr. aur. bor.]", "desc": "[Сообщение о наблюдениях, подтверждающих электрическую природу северного сияния]", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. [Tab. cum phaen. fulmin.]", "desc": "[Таблица с записью грозовых явлений за 1744—1748 гг.]", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. [Ad praem. 1765]", "desc": "Задача на премию [Петербургской Академии Наук на 1765 г.]", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. [Ad praem. 1756]", "desc": "Задачи [на премию Петербургской Академии Наук на 1756 г.]", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. [Med. de via nav. determ.]", "desc": "Meditationes de via navis in mari certius determinanda praelectae in publico conventu Academiae Scientiarum imperialis Petropolitanae die VIII mai", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Meth. inven. et descr. lin. merid.", "desc": "Methodus nova, facillima et certissima, inveniendi et describendi lineam meridionalem, auctore M. Lomonosow", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. De tub. nyctopt.", "desc": "Problema physicum de tubo nyctoptico", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Probl. pro trib. praem. propon.", "desc": "Problema pro tribuendo praemio proponendum", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. Repres. semit. Ven. 1761", "desc": "Representatio semitae Veneris anno 1761", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. [Not. ad querel. Aepini]", "desc": "[Записка, читанная в заседании Академического собрания 8 декабря 1760 г. по поводу жалоб Ф. Эпинуса на критику, которой Ломоносов подверг его статью «Известие о наступающем прохождении Венеры между Солнцем и Землею»]", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. [De cult. tub. optic.]", "desc": "[Об усовершенствовании зрительных труб]", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });
db.taxonomymodel.insertOne({ "code": "Lomon. [Comput. telescop. monocul. fragm.]", "desc": "[Отрывок с расчетом однозеркального телескопа]", "parentId": ObjectId("5fff6e9258d88145a0a8ba19") });